### ISSUE TITLE
[Marker.io] Clickable area below the menus in the navigation is too large

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#16]
[![Screenshot_2024-04-29_06-11-17.png](https://mrkr.io/s/662f3a0575a3ca5a6f3a2095/2)](https://mrkr.io/s/662f3a0575a3ca5a6f3a2095/0)

Steps to reproduce:
1) go to https://carbn-stg.webflow.io/
2) move the pointer below the menus like "advice" in the main navigation
it should be little away and below the menu
(as shown in recordings)

Actual result: clickable area is too large as the pointer is turning into hand icon and user can click it. 

Expected result: this should be improved. the clickable area below the menus should be reduced.

recording:
https://go.screenpal.com/watch/cZfU16VMuAI

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/](https://carbn-stg.webflow.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
it is fixed only for menus like advice, vehicle etc in main navigation but still not working for "Menu"  (on top left). clickable area below it is still very large.

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2) - 💬 **Himanshu Chawla** commented:

> Fixed

[Reply here](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2)

**Comment by vinod-ku1989** [comment]
- still seeing the same behavior. clickable area below the "menu" is still large.  move the pointer below the "menu" on top left andnotice the pointer

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2) - 💬 **Himanshu Chawla** commented:

> Updated now please check

[Reply here](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f3a0575a3ca5a6f3a2098_58a8811281b5d7f2) - This issue was marked as **✅ Resolved** in Marker.io
