### ISSUE TITLE
[Marker.io] mobile- users have to scroll up in order to see the content when they click "learn more" in the calculator.

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#23]
[![Screenshot_2024-04-29_11-26-11.png](https://mrkr.io/s/662f83d37863bbe3a3c44bd2/2)](https://mrkr.io/s/662f83d37863bbe3a3c44bd2/0)

Steps to reproduce:
1) open the site in mobile
2) go to home page and scroll to calculator
3) click learn more button
4) scroll up

Actual result: users have to scroll up in order to see the content.

Expected result:if possible, this should be improved. 

video link:
https://drive.google.com/file/d/1g7YI44wT987nyRQjibBM016OnoHBndRk/view?usp=drivesdk

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/662f83d37863bbe3a3c44bd5_8d75f6a1ea697158?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/](https://carbn-stg.webflow.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/662f83d37863bbe3a3c44bd5_8d75f6a1ea697158?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>412 x 892</td></tr><tr><td><strong>OS</strong></td><td>Android 11.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>412 x 756</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2.625x</td></tr></table>

**Comment by vinod-ku1989** [comment]
same behaviour is still observed. they still have to scroll up in order to see the content

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f83d37863bbe3a3c44bd5_8d75f6a1ea697158) - 💬 **Himanshu Chawla** commented:

> Done, check please

[Reply here](https://app.marker.io/i/662f83d37863bbe3a3c44bd5_8d75f6a1ea697158)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f83d37863bbe3a3c44bd5_8d75f6a1ea697158) - This issue was marked as **✅ Resolved** in Marker.io
