### ISSUE TITLE
[Marker.io] phone field is accepting the alphabets on the "enquire now" form

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#24]
[![Screenshot_2024-04-29_11-30-39.png](https://mrkr.io/s/662f84dfbe1c7d9796ffea68/2)](https://mrkr.io/s/662f84dfbe1c7d9796ffea68/0)

Steps to reproduce:
1) open https://carbn-stg.webflow.io/
2) click the contact us button shown on bottom right side 
3) click and click in the phone field
4) enter alphabets

Actual result:
field is accepting the alphabets

Expected result:
user should not be able to enter alphabets.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/662f84dfbe1c7d9796ffea6b_e2f7011b28737608?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/](https://carbn-stg.webflow.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/662f84dfbe1c7d9796ffea6b_e2f7011b28737608?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1517 x 712</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by vinod-ku1989** [comment]
the error message shown now is not correct. it says : please match the format requested. we don't have any format on the phone field.
![match1](https://github.com/Himanshu201209/carbn/assets/29223268/f8faff5c-617f-400a-bf76-25ecca1013a0)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f84dfbe1c7d9796ffea6b_e2f7011b28737608) - 💬 **Himanshu Chawla** commented:

> Updated validation across forms

[Reply here](https://app.marker.io/i/662f84dfbe1c7d9796ffea6b_e2f7011b28737608)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/662f84dfbe1c7d9796ffea6b_e2f7011b28737608) - This issue was marked as **✅ Resolved** in Marker.io
