### ISSUE TITLE
[Marker.io] Mobile- issues related to menu on mini devices

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#34]
[![Screenshot_2024-04-30_03-36-22.png](https://mrkr.io/s/663067368ef3742d412e37fe/2)](https://mrkr.io/s/663067368ef3742d412e37fe/0)

Steps to reproduce:
1) open site in mini devices like iPhone 12 mini
2) click menu on left
3) notice the bottom of the menu( not much space is there when address bar is present)
4) scroll down a little so that address bar gets hidden
5) now again open the menu and notice the modal at the bottom

Actual result: 1) when address bar is there, there is not much space between last menu and address bar
2) when address bar is hidden, modal does not cover entire screeen

Expected result: this should be improved

iPhone 12 mini , safari , ios 17.1.2,

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/contact](https://carbn-stg.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Safari 17.1.2</td></tr><tr><td><strong>Screen Size</strong></td><td>375 x 812</td></tr><tr><td><strong>OS</strong></td><td>iOS 17.1.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>375 x 710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc) - 💬 **Vinod** commented:

> here's the video link:
> https://drive.google.com/file/d/1zHAZhav9ITYpyG4lM7RotEDxbz74W94a/view?usp=sharing

[Reply here](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc)

**Comment by vinod-ku1989** [comment]
now when the address bar is visible, contact menu on the modal is not visible and (user cannot scroll also in order to see that)
![Repudia Non Nisi Non jpeg](https://github.com/Himanshu201209/carbn/assets/29223268/c8cb91c9-6471-446e-98c9-5becde5dcf10)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc) - 💬 **Himanshu Chawla** commented:

> Done

[Reply here](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/663067368ef3742d412e3801_cfd3468228d458dc) - This issue was marked as **✅ Resolved** in Marker.io
