### ISSUE TITLE
[Marker.io] suggestion: we can show some text message when no results are found after selecting the filters on news page

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#36]
[![Screenshot_2024-04-30_04-01-07.png](https://mrkr.io/s/66306d03c17541828b912aae/2)](https://mrkr.io/s/66306d03c17541828b912aae/0)

Steps to reproduce:
1) go to https://carbn-stg.webflow.io/news
2) choose "carshare" filter

Actual result:notice that no message  is shown

Expected result: we can show some message like "No results found " or "No items found"

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66306d03c17541828b912ab1_fb0224ae4f28c5fe?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/news](https://carbn-stg.webflow.io/news)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66306d03c17541828b912ab1_fb0224ae4f28c5fe?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
not able to retest this as all the filters are now showing some results

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66306d03c17541828b912ab1_fb0224ae4f28c5fe) - 💬 **Himanshu Chawla** commented:

> Added

[Reply here](https://app.marker.io/i/66306d03c17541828b912ab1_fb0224ae4f28c5fe)

—
**Attachments:**

- [image.png](https://files.marker.io/f/65fb7ea27d9ebfe5c74463e7/6634dd65861be078f2ee83a9) (*59.3KB*)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66306d03c17541828b912ab1_fb0224ae4f28c5fe) - This issue was marked as **✅ Resolved** in Marker.io
