### ISSUE TITLE
[Marker.io] inconsistent behaviour of "contact us" button 

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#39]
[![Screenshot_2024-04-30_04-40-25.png](https://mrkr.io/s/6630763966985585ea6f2153/2)](https://mrkr.io/s/6630763966985585ea6f2153/0)

Steps to reproduce:
1) go to home page
2) notice the contact us button on bottom right and scroll down
3) go to any other page like technology
4) repeat step 2
5) go to home page in mobile browser
6) notice the same contact us button and scroll down

Actual result:
on desktop (home page), it scrolls but on (mobile), it remains fixed.
on desktop (other pages), the button remains fixed.

Expected result:
I think it should be consistent on all pages.

video:
https://go.screenpal.com/watch/cZfvfgVMxoN

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/](https://carbn-stg.webflow.io/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399) - 💬 **Himanshu Chawla** commented:

> Pending
> 

[Reply here](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399) - 💬 **Himanshu Chawla** commented:

> Done

[Reply here](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399) - 💬 **Himanshu Chawla** commented:

> We are just fixing the button on Homepage here both mobile and desktop
> 

[Reply here](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399)

**Comment by vinod-ku1989** [comment]
on mobile: the contact us button is missing on other pages like advice, finance now.

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6630763966985585ea6f2156_eff88fa2d5f32399) - This issue was marked as **✅ Resolved** in Marker.io
