### ISSUE TITLE
[Marker.io] firefox issue : box height of one of the tile box is different from other tiles on case studies page

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#40]
[![Screenshot_2024-04-30_05-03-24.png](https://mrkr.io/s/66307b9cb5f6587697af8f27/2)](https://mrkr.io/s/66307b9cb5f6587697af8f27/0)

Steps to reproduce:
1) go to https://carbn-stg.webflow.io/case-studies
2) scroll down and notice the 2nd tile ( 2nd row)

Actual result: box height is different and is more than other tiles.
note: marker tool did not capture this. see the other screenshot.

Expected result: height should be same

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/case-studies](https://carbn-stg.webflow.io/case-studies)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 125.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 615</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

---
**Attached files:** 

**-** [box height.png (197.2KB)](https://files.marker.io/f/65fb7ea27d9ebfe5c74463e7/66307b9cb5f6587697af8f29)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef) - 💬 **Vinod** commented:

> also observed for the 3rd tile ( 1st row)
> 

[Reply here](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef)

—
**Attachments:**

- [boxx height 2.png](https://files.marker.io/f/65fb7ea27d9ebfe5c74463e7/66307c417df2a634d482087e) (*365.2KB*)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef) - 💬 **Himanshu Chawla** commented:

> Pending

[Reply here](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef)

**Comment by Druhin13** [comment]
@vinod-ku1989 please retest this

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66307b9cb5f6587697af8f2c_e134bf331d5610ef) - This issue was marked as **✅ Resolved** in Marker.io
