### ISSUE TITLE
[Marker.io] Tablet— no padding on the right side of Dunedin location tile on contact page

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#53]
[![Screenshot_2024-04-30_07-33-05.png](https://mrkr.io/s/66309eb1192e40f0ce940a9d/2)](https://mrkr.io/s/66309eb1192e40f0ce940a9d/0)

Steps to reproduce:1) go to contact page in tablet devices
2) notice the Dunedin location tile
3) notice the padding on right side

Actual result: there is no padding on the right side

Expected result: it should be there

Also observed on browserstack iPad Pro 12.9.2021 safari 17 portrait mode

---

**Reported by:** Vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66309eb1192e40f0ce940aa0_349b2a5370f7e09a?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/contact](https://carbn-stg.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66309eb1192e40f0ce940aa0_349b2a5370f7e09a?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>tablet</td></tr><tr><td><strong>Browser</strong></td><td>Safari 17.3.1</td></tr><tr><td><strong>Screen Size</strong></td><td>768 x 1024</td></tr><tr><td><strong>OS</strong></td><td>iOS 17.3.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1170 x 798</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by vinod-ku1989** [comment]
still seeing the same behaviour.

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66309eb1192e40f0ce940aa0_349b2a5370f7e09a) - 💬 **Himanshu Chawla** commented:

> Done

[Reply here](https://app.marker.io/i/66309eb1192e40f0ce940aa0_349b2a5370f7e09a)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66309eb1192e40f0ce940aa0_349b2a5370f7e09a) - This issue was marked as **✅ Resolved** in Marker.io
