### ISSUE TITLE
[Marker.io] user is able to enter alphabets in the phone field on the contact form

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#54]
[![Screenshot_2024-04-30_07-35-18.png](https://mrkr.io/s/66309f36c17541828b920582/2)](https://mrkr.io/s/66309f36c17541828b920582/0)

Steps to reproduce:
1) go to https://carbn-stg.webflow.io/contact
2) click in the phone field and enter alphabetts

Actual result: user is able to enter the alphabets in the phone field

Expected result: user should not be able to enter the alphabets in phone field

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/contact](https://carbn-stg.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db) - 💬 **Himanshu Chawla** commented:

> Try to submit please, validation works when you try to submit the form

[Reply here](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db)

**Comment by vinod-ku1989** [comment]
validation message is not proper. it says : please match the format requested. we are not showing any format on phone field.

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db) - 💬 **Himanshu Chawla** commented:

> Updated

[Reply here](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66309f36c17541828b920585_6b62b081158e61db) - This issue was marked as **✅ Resolved** in Marker.io
