### ISSUE TITLE
[Marker.io] mobile : numerical keypad is shown when user clicks in email field in contact form on careers page. hence not able to submit form

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#79]
[![Screenshot_2024-04-30_13-39-54.png](https://mrkr.io/s/6630f4a9012dfdf014d9044f/2)](https://mrkr.io/s/6630f4a9012dfdf014d9044f/0)

Steps to reproduce:
1) open careers page in mobile browsers
2) scroll down to  contact form
3) click email field and notice the keypad

Actual result: numerical keypad is shown

Expected result: user should see alphanumerical keypad

also seen on ios devices too.

this should be fixed else they wont be able to submit the form

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/6630f4aa012dfdf014d90455_6f816d140a873ad2?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/careers](https://carbn-stg.webflow.io/careers)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6630f4aa012dfdf014d90455_6f816d140a873ad2?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>mobile</td></tr><tr><td><strong>Browser</strong></td><td>Chrome Mobile 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>412 x 892</td></tr><tr><td><strong>OS</strong></td><td>Android 11.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>412 x 756</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2.625x</td></tr></table>

---
**Attached files:** 

**-** [Screenshot_20240430-190604_Chrome.jpg (406.1KB)](https://files.marker.io/f/65fb7ea27d9ebfe5c74463e7/6630f4aa012dfdf014d90452)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6630f4aa012dfdf014d90455_6f816d140a873ad2) - 💬 **Himanshu Chawla** commented:

> This looks fine on my end. Please check again

[Reply here](https://app.marker.io/i/6630f4aa012dfdf014d90455_6f816d140a873ad2)

**Comment by vinod-ku1989** [comment]
looks like it got fixed when some other issue was fixed. working now

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6630f4aa012dfdf014d90455_6f816d140a873ad2) - This issue was marked as **✅ Resolved** in Marker.io
