### ISSUE TITLE
[Marker.io] inconsistent use of vehicle and carshare

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#83]
[![Screenshot_2024-04-30_14-40-40.png](https://mrkr.io/s/663102e87863bbe3a3cd9340/2)](https://mrkr.io/s/663102e87863bbe3a3cd9340/0)

Steps to reproduce:
1) go to site
2) open the enquire form
3) click service interested in field
4) notice the carshare value
5) check the same field on contact form too

Actual result: carshare is used at some places on site and vehicle is used at some places.

Expected result: I think it should now be "vehicle" and it should be consistently used on site.

also need to update filters on case studies and news page.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/services/finance](https://carbn-stg.webflow.io/services/finance)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Safari 17.3.1</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 761</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
still not fixed on the contact page. ( "service interested in" field). it is stil showing "carshare"

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba) - 💬 **Himanshu Chawla** commented:

> Done

[Reply here](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba)

**Comment by vinod-ku1989** [comment]
still seeing same behaviour on contact page. please check if it is deployed or not (after fixing) or fix it if the fix is not working.

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba) - 💬 **Himanshu Chawla** commented:

> Updated on careers page as well

[Reply here](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/663102e87863bbe3a3cd9343_18765708a5e4dbba) - This issue was marked as **✅ Resolved** in Marker.io
