### ISSUE TITLE
[Marker.io] gap on the right side of the page looks quite big on higher resolutions

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#86]
[![Screenshot_2024-04-30_16-45-44.png](https://mrkr.io/s/6631203802eeb6d35d38d952/2)](https://mrkr.io/s/6631203802eeb6d35d38d952/0)

Steps to reproduce:
1) open site in higher resolutions like 3840*2160
2) scroll down to section below the header video or image
3) notice the space on the right side

Actual result:
space looks quite big

Expected result:
if possible, this needs to be improved..

note: this is observed on most of the pages.

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/careers](https://carbn-stg.webflow.io/careers)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3840 x 2160</td></tr><tr><td><strong>OS</strong></td><td>Windows 11 (15.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840 x 2025</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
this is fixed only on careers page. same behaviour is still observed on other pages like finance,advice, technology, zilch , about us etc.
![sp](https://github.com/Himanshu201209/carbn/assets/29223268/2f9b9707-9bc3-4282-873f-865580f965d6)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985) - 💬 **Himanshu Chawla** commented:

> Done

[Reply here](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985)

**Comment by vinod-ku1989** [comment]
![gapp](https://github.com/Himanshu201209/carbn/assets/29223268/0dadb738-ead6-4ae6-b817-5b3a4ca77612)

still seeing lot of gap on the right side of the content ( content below header video/image) on abouts us, service pages like finance, advice, tech etc.

if it's not possible to improve, we can ignore it because it should not break other things.

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985) - 💬 **Himanshu Chawla** commented:

> Check again please

[Reply here](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6631203802eeb6d35d38d955_9523a526e2f2f985) - This issue was marked as **✅ Resolved** in Marker.io
