### ISSUE TITLE
[Marker.io] users have to scroll up in order to see the thank you message after submitting the contact form

### ISSUE THREAD

**Issue by himanshu201209** [himanshu201209/carbn#95]
[![Screenshot_2024-05-01_03-28-48.png](https://mrkr.io/s/6631b6f0fe37d74f9d3fcfaa/2)](https://mrkr.io/s/6631b6f0fe37d74f9d3fcfaa/0)

Steps to reproduce:
1) go to contact page
2) enter only the required fields
3) submit
4) try to see the success message

Actual result: users have to scroll up in order to see the message. this is happening even when user has not entered any text in message field.

Expected result: if possible, this should be improved. 

---

**Reported by:** vinod (vinod@na.studio) - [Contact via Marker.io](https://app.marker.io/i/6631b6f0fe37d74f9d3fcfad_70dc2cd46978beff?advanced=1&comments=1)

**Source URL:** [https://carbn-stg.webflow.io/contact](https://carbn-stg.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6631b6f0fe37d74f9d3fcfad_70dc2cd46978beff?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 124.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
still same behaviour is observed

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6631b6f0fe37d74f9d3fcfad_70dc2cd46978beff) - 💬 **Himanshu Chawla** commented:

> Test again once

[Reply here](https://app.marker.io/i/6631b6f0fe37d74f9d3fcfad_70dc2cd46978beff)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6631b6f0fe37d74f9d3fcfad_70dc2cd46978beff) - This issue was marked as **✅ Resolved** in Marker.io
